# Generated by Django 5.2.5 on 2025-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
