# Generated by Django 5.2.5 on 2025-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orders_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Model/'),
        ),
    ]
