# Generated by Django 5.2.5 on 2025-09-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orders_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
