# Generated by Django 5.2.5 on 2025-10-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_image_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
    ]
