# Generated by Django 5.2.5 on 2025-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_orders_color_remove_orders_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
