# Generated by Django 5.2.5 on 2025-10-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orders_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
            ],
        ),
    ]
