# Generated by Django 5.2.5 on 2025-10-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orderitem_product_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
        ),
    ]
