# Generated by Django 5.2.5 on 2025-10-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_orders_total_alter_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
    ]
