# Generated by Django 5.2.8 on 2025-11-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_orderitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(null = True,blank=True, to='main.orderitem'),
        ),
    ]
